### ISSUE TITLE
Won't compile on FreeBSD 7.3

### ISSUE THREAD

**Issue by gfarm-admin** [oss-tsukuba/gfarm#138]
What I do:  

    
    wget --no-check-certificate https://downloads.sourceforge.net/project/gfarm/gfarm_v2/2.4.0/gfarm-2.4.0.tar.gz
    tar -xzf gfarm-2.4.0.tar.gz
    cd gfarm-2.4.0/
    ./configure
    gmake
    

gmake fails with the following message:  

    
    In file included from ./config_server.c:9:
    ../../../lib/libgfarm/gfutil/gfutil.h:20: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'gfarm_send_no_sigpipe'
    gmake[3]: *** [config_server.lo] Error 1
    gmake[3]: Leaving directory `/tmp/gfarm-2.4.0/lib/libgfarm/gfarm'
    

Editing "lib/libgfarm/gfutil/gfutil.h" and replacing "ssize_t" with "size_t" helps.  

Reported by: ArtemGr

Original Ticket: [gfarm/tickets/138](https://sourceforge.net/p/gfarm/tickets/138)
